<a href="https://colab.research.google.com/github/merazlab/python/blob/master/hd5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#HDF5- Hierachical Data Formats

it support large complex hetrogenious data

![alt text](https://www.neonscience.org/sites/default/files/images/HDF5/hdf5_structure4.jpg)

HDF5 file format is self describing. it means each file or group and dataset can have associated with metadata. that metadata desccribe what the data are.

##Saving and reading

In [0]:
import h5py
import numpy as np

In [5]:
arr1 = np.random.randint(1, 4, (2, 3))
arr2 = np.random.randint(1, 4, (1, 2))
print(arr1)
print(arr2)

[[2 3 1]
 [1 2 2]]
[[2 1]]


In [0]:
with h5py.File('mynewh5.hdf5', 'w') as f:
  f.create_dataset("dataset1", data = arr1)
  f.create_dataset("dataset2", data = arr2)



##Reading

In [9]:
with h5py.File('mynewh5.hdf5', 'r') as h5:
  print(h5.keys())

<KeysViewHDF5 ['dataset1', 'dataset2']>


Find which datasets are in hdf file  use below method

In [11]:
with h5py.File('mynewh5.hdf5', 'r') as hdf:
  data = hdf.get("dataset1")
  print(type(data))

<class 'h5py._hl.dataset.Dataset'>


In [12]:
with h5py.File('mynewh5.hdf5', 'r') as hdf:
  data_h5 = hdf.get("dataset1")
  data = np.array(data_h5)
  print(data)

[[2 3 1]
 [1 2 2]]


In [14]:
f =  h5py.File('mynewh5.hdf5', 'r')
data_h5 = f.get("dataset1")
data = np.array(data_h5)
print(data)
f.close()

[[2 3 1]
 [1 2 2]]


In [0]:
f = h5py.File('mynewh5.hdf5', 'r')
data_h5 = f['dataset1']


In [22]:
print(data_h5.dtype)
f.close()

int64


##Group

In [0]:
arr1 = np.random.randint(1, 4, (2, 3))
arr2 = np.random.randint(1, 4, (1, 2))
arr3 = np.random.randint(1, 4, (5))
arr4 = np.random.randint(1, 4, (3, 2, 2))

In [0]:
with h5py.File("myh5file.hdf5", "w") as hdf:
  g1 = hdf.create_group("group1")
  g1.create_dataset("darr1", data = arr1)
  g1.create_dataset("darr2", data = arr2)

  g2 = hdf.create_group("group2/subgroup1")
  g2.create_dataset("darr3", data = arr3)
  g2.create_dataset("darr4", data = arr4)


In [39]:
with h5py.File("myh5file.hdf5", "r") as f:
  print(f.items())
  print(list(f.items()))


ItemsViewHDF5(<HDF5 file "myh5file.hdf5" (mode r)>)
[('group1', <HDF5 group "/group1" (2 members)>), ('group2', <HDF5 group "/group2" (1 members)>)]


In [43]:
with h5py.File("myh5file.hdf5", "r") as f:
  data_h5 = f.get("group1")
  data = list(data_h5.items())
  print(data)
  

[('darr1', <HDF5 dataset "darr1": shape (2, 3), type "<i8">), ('darr2', <HDF5 dataset "darr2": shape (1, 2), type "<i8">)]


In [46]:
with h5py.File("myh5file.hdf5", "r") as f:
  data_g1 = f.get("group1")
  a2 = np.array(data_g1.get("darr2"))
  print(a2)
  

[[3 1]]


##Compression

In [0]:
with h5py.File("compressfile", "w") as hdf:
  hdf.create_dataset("data1", data = arr1, compression='gzip')