Module-11


#**Numpy Arrrary**

In [0]:
import numpy as np
import pandas as pd

Numpy Data Types
Numpy has the following data types: 
- ```int```
- ```float```
- ```complex```
- ```bool```
- ```string```
- ```unicode```
- ```object```

The numeric data types have various precisions like 32-bit or 64-bit. 

Numpy data types can be represented using either __Type__ or __Type Code__

In [3]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

Data types can be defined at creating the numpy array and converted to other types later. 

You can use either _type, type code_ or _```np``` dot_ methods to define the data type of an array, but when you use ```np``` dot method to define the data type, it can only follow _type_ rather than _type code_.

In [6]:
arr = np.array([1,2,3], dtype='f4')
print(arr.dtype)
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
print(arr.dtype)

float32
float32


In [7]:
arr = np.array([1,2,3], dtype=np.float32)
print(arr.dtype)

float32
ERROR! Session/line number was not unique in database. History logging moved to new session 59


##Type Conversion

```astype``` method: convert the data type of an array to other data types. 

Notice that ```astype``` returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

![alt text](https://user-images.githubusercontent.com/90008/60764516-8d059e80-a059-11e9-87b6-459c3f6eb5b1.png)

In [8]:
arr = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
print('Data Type After Conversion: ' + str(arr.dtype))

Original Data Type: int16
Data Type After Conversion: float32


Overflow in downgrade

In [9]:
# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 256]
np array after type conversion: [126 127   0]


String / Unicode Data Types

In [10]:
# An example of truncated string
s = np.array(['abc', 'defg'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U3')
print(s)

[b'abc' b'def']
['abc' 'efg']


#Numpy Array  info

In [0]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int16)

In [0]:
np.info(arr)

In [44]:
print(arr.dtype)
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr.size) #number of elements in an array
print(arr.itemsize) #number of bytes of each element in an array
print(arr.nbytes) #memory size of an array (in byte)

int16
(2, 3)
2
2
6
2
12


In [45]:
print(arr.dtype())

TypeError: ignored

print(arr.dtype())

#Creating Array

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [12]:
a = np.array([1,2,3,4,5])
b = np.array((1,2,3,4,5))
c = np.array(range(10))
print(a, type(a))
print(b, type(b))
print(c, type(c))


[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


Create an array with specified data type

In [13]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


create array within specified range

In [14]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


Create an array of evenly spaced numbers within specified range

In [16]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


Create an array of random values of given shape


In [17]:
arr = np.random.rand(3, 3) #return the value range[0, 1]
print(arr)

[[0.67248749 0.7399373  0.52089913]
 [0.96485619 0.63587942 0.83927755]
 [0.51132711 0.04374254 0.66940205]]


np.zeros(): create array of all zeros in given shape

In [18]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


np.zeros_like(): create array of all zeros with the same shape and data type as the given input array

In [21]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype), type(zeros))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64 <class 'numpy.ndarray'>


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [22]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [23]:
empty = np.empty((5,5))
print(empty)

[[0.00000000e+000 8.25089629e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [1.16095484e-028 2.93494599e+222 1.03063392e-113 5.46817797e-095
  1.06259729e+223]
 [7.92680158e-061 7.35874688e+223 4.62379315e+252 3.97062310e+246
  2.77621464e+184]
 [1.47763669e+248 1.78879622e+161 5.18775165e+141 3.51022257e+151
  1.30424409e-142]
 [1.70546600e+256 1.75718683e+243 9.95923263e-143 1.91077948e+214
  7.34295013e+223]]


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [24]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat

In [25]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [26]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [27]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [28]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [29]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#An examle of diagonal  ofset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [31]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [32]:
arr = np.random.rand(3,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.50943328 0.84557814 0.89562722]
 [0.85679057 0.06980709 0.26302962]
 [0.95870131 0.16434947 0.76988494]]
Values on the diagonal: [0.50943328 0.06980709 0.76988494]


In [33]:
# Not necessarily to be a square matrix
arr = np.random.rand(3,2)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.89597232 0.19258657]
 [0.39691419 0.19477115]
 [0.28903743 0.90752571]]
Values on the diagonal: [0.89597232 0.19477115]


In [34]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Random / Sampling Method

In [1]:
a = np.random.seed(2)
print(a)

NameError: ignored

In [0]:
import numpy as np

#Math Function

In [11]:
arr = np.random.randint(0, 5, (2, 3))
print(arr)

[[1 3 2]
 [3 3 1]]


In [12]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[11 13 12]
 [13 13 11]]
[[-9 -7 -8]
 [-7 -7 -9]]
[[10 30 20]
 [30 30 10]]
[[0.1 0.3 0.2]
 [0.3 0.3 0.1]]


In [13]:
# the above operations can be performed using numpy built-in functions

arr1 = arr
print(np.add(arr1, 10))

print(np.subtract(arr1, 10))

print(np.multiply(arr1, 10))


[[11 13 12]
 [13 13 11]]
[[-9 -7 -8]
 [-7 -7 -9]]
[[10 30 20]
 [30 30 10]]


In [14]:
# which can save memory as the output can be stored in the original array rather than assigning new memory

arr1 = arr
np.add(arr1, 10, out=arr1)
print(arr1)
print(arr)

# np.subtract(arr1, 10, out=arr1)
# print(arr1)
# arr1 = arr
# np.multiply(arr1, 10, out=arr1)
# print(arr1)

[[11 13 12]
 [13 13 11]]
[[11 13 12]
 [13 13 11]]


Element-wise exponent

In [15]:
print(np.exp(arr))

[[ 59874.1417152  442413.39200892 162754.791419  ]
 [442413.39200892 442413.39200892  59874.1417152 ]]


Element-wise atural log

In [16]:
print(np.log(arr)) 

[[2.39789527 2.56494936 2.48490665]
 [2.56494936 2.56494936 2.39789527]]


In [17]:
# base 2
print(np.log2(arr))  

[[3.45943162 3.70043972 3.5849625 ]
 [3.70043972 3.70043972 3.45943162]]


In [18]:
#Element-wise square root
print(np.sqrt(arr))

[[3.31662479 3.60555128 3.46410162]
 [3.60555128 3.60555128 3.31662479]]


In [20]:
#element-wise sin and cosine
print(np.sin(arr)) #arr in radian

[[-0.99999021  0.42016704 -0.53657292]
 [ 0.42016704  0.42016704 -0.99999021]]


##sum along specific access

In [24]:
arr1 = np.random.randint(0, 9, (2, 3))
arr2 = np.random.randint(0, 9, (2, 3))

print(arr1)
print(arr2)

[[8 4 1]
 [6 2 2]]
[[5 2 0]
 [7 0 5]]


In [28]:
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1))
print((np.sum(arr1)))

[14  6  3]
[13 10]
23


In [27]:
print(np.add(arr1, arr1))

[[16  8  2]
 [12  4  4]]


##Find min or max

In [29]:
print(np.min(arr1, axis=0))
print(np.max(arr1, axis=0))
print(np.min(arr1))
print(np.max(arr1))

[6 2 1]
[8 4 2]
1
8


find indices of min max

In [30]:
print(np.argmin(arr1, axis=0))
print(np.argmax(arr1, axis=0))
print(np.argmin(arr1))
print(np.argmax(arr1))

[1 1 0]
[0 0 1]
2
0


element-wise min or max between two array

In [31]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


##mean and standard devision

In [34]:
arr1 = np.random.randint(0, 5, (2, 3))

print(arr1)

[[1 3 1]
 [1 4 3]]


In [43]:
print(np.mean(arr1))
print(np.mean(arr1, axis=0))
b = np.mean(arr1, axis=0)
print(b.dtype)
print(np.mean(arr1, axis=0).dtype)

2.1666666666666665
[1.  3.5 2. ]
float64
float64


median

In [45]:
print(np.median(arr1))  #middle element in the list
print(np.median(arr1, axis=0)) 


2.0
[1.  3.5 2. ]


Variance

In [46]:
print(np.std(arr1))
print(np.std(arr1, axis=0))
print(np.var(arr1))
print(np.var(arr1, axis=0))

1.2133516482134197
[0.  0.5 1. ]
1.4722222222222223
[0.   0.25 1.  ]


![alt text](https://i.ytimg.com/vi/xPu1m2xfhVc/hqdefault.jpg)

[Covariance](http://www.sharetechnote.com/html/Handbook_EngMath_CovarianceMatrix.html)

In [51]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[1, 2], [3, 3]])
print(np.var(a))
print(np.cov(a))
print(np.cov(a, a))
print(np.cov(a, b))

1.25
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[0.5 0.5 0.5 0. ]
 [0.5 0.5 0.5 0. ]
 [0.5 0.5 0.5 0. ]
 [0.  0.  0.  0. ]]


Correlation

In [54]:
print(np.corrcoef(a))
print(np.corrcoef(a, a))
print(np.corrcoef(a, b))


[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.  1.  1. nan]
 [ 1.  1.  1. nan]
 [ 1.  1.  1. nan]
 [nan nan nan nan]]


/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


Comparison

In [56]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
print(arr1 == arr2)    
print(arr1 < 3)
print(type(arr1 < arr2))

[False False  True False False]
[ True  True False False False]
<class 'numpy.ndarray'>


Split Integer and fractional part

In [58]:
arr = np.random.rand(5) *10
print(arr)

[6.39003196 7.21189302 8.3372475  2.25074934 6.3921955 ]


In [61]:
fractional, integral = np.modf(arr) #return fractional then integrall part
print(integral) 
print(fractional)

[6. 7. 8. 2. 6.]
[0.39003196 0.21189302 0.3372475  0.25074934 0.3921955 ]


#Slicing/Indexing/reshape

In [67]:
a = np.array(range(6))
b = np.array(range(6)).reshape((6)) 
c = np.array(range(6)).reshape((1, 6))
d = np.array(range(6)).reshape((6, 1)) 

print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))

[0 1 2 3 4 5] <class 'numpy.ndarray'>
[0 1 2 3 4 5] <class 'numpy.ndarray'>
[[0 1 2 3 4 5]] <class 'numpy.ndarray'>
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] <class 'numpy.ndarray'>


###select element

In [77]:
d1 = np.random.randint(0, 9, (6))
d2 = np.random.randint(0, 9, (2, 3))
d3 = np.random.randint(0, 9, (3, 2, 4))
print(d1)
print(d2)
print(d3)


[0 3 4 4 3 6]
[[3 3 8]
 [7 6 0]]
[[[5 0 7 2]
  [6 4 7 7]]

 [[6 0 2 1]
  [6 7 2 3]]

 [[4 8 4 1]
  [5 1 7 5]]]


In [78]:
print(d1[3])
print(d2[0, 2]) #both are same print(d2[0][2])
print(d3[1, 0, 2])

4
8
2


In [80]:
print(d2[0])
print(d2[0, :]) #same above
print(d2[1])
print(d2[1, :]) #same above

[3 3 8]
[3 3 8]
[7 6 0]
[7 6 0]


In [81]:
print(d2[:, 0])
print(d2[:, 1])
print(d2[:, 2])


[3 7]
[3 6]
[8 0]


var[lower:upper:step]

In [84]:
d2 = np.random.randint(0, 9, (3, 4))
print(d2)

[[4 4 5 8]
 [2 8 7 1]
 [3 4 5 7]]


In [87]:
#along axis = 1
print(d2[0:2])
print(d2[0::1]) #stride 1
print(d2[0::2]) #stride 2 

[[4 4 5 8]
 [2 8 7 1]]
[[4 4 5 8]
 [2 8 7 1]
 [3 4 5 7]]
[[4 4 5 8]
 [3 4 5 7]]


In [88]:
#along axis = 2
print(d2[:, 2])
print(d2[:, 0:2]) #stride 1
print(d2[:, 0:4:2]) #stride 2 

[5 7 5]
[[4 4]
 [2 8]
 [3 4]]
[[4 5]
 [2 7]
 [3 5]]


In [89]:
print(d2)

[[4 4 5 8]
 [2 8 7 1]
 [3 4 5 7]]


In [91]:
print(d2[0::2, 0::3]) #select all corner element

[[4 8]
 [3 7]]


#Fancy indexing

In [102]:
d1 = np.random.randint(0, 9, (10)) 
print(d1)

[7 4 7 5 2 4 1 7 0 5]


In [103]:
indices = [1, 3, 5]
print(d1[indices])

[4 5 4]


In [104]:
d1[indices] = 99
print(d1)

[ 7 99  7 99  2 99  1  7  0  5]


index with boolean

In [105]:
mask = np.array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0], dtype=bool)
y = d1[mask]
print(y)

[99  2  1]


Now in 2D

In [106]:
d2 = np.random.randint(0, 9, (3, 5)) 
print(d2)

[[2 6 5 6 2]
 [0 2 6 3 2]
 [1 1 4 1 7]]


In [110]:
print(d2[[0, 1, 2],
         [2, 3, 4]])

[5 3 7]


In [111]:
print(d2[:,
         [2, 3, 4]])

[[5 6 2]
 [6 3 2]
 [4 1 7]]


In [113]:
mask = np.array([1, 0, 0, 1, 0], dtype=bool)
print(d2[1, mask])

[0 3]


###Find element/indices by condition

In [0]:
import numpy as np

In [3]:
d2 = np.random.randint(0, 9, (4, 5)) 
print(d2)

[[7 6 7 7 0]
 [0 3 2 2 1]
 [0 4 6 0 8]
 [1 2 7 0 2]]


In [4]:
print(d2[d2 > 5]) #return the value and flattened the output

[7 6 7 7 6 8 7]


In [6]:
print(np.where(d2[d2 > 5])) #return indices

(array([0, 1, 2, 3, 4, 5, 6]),)


In [12]:
print(np.argwhere(d2 > 5)) #return indices

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [2 2]
 [2 4]
 [3 2]]


In [11]:
print(np.where(d2 > 5, 9, 1)) 

[[9 9 9 9 1]
 [1 1 1 1 1]
 [1 1 9 1 9]
 [1 1 9 1 1]]


##Broadcasting

[numpy doc](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)





Eroor found

"ValueError: shape mismatch: objects cannot be
broadcast to a single shape"

In [14]:
d2 = np.random.randint(0, 9, (4, 3)) 
print(d2)

[[5 8 0]
 [3 6 2]
 [1 4 5]
 [1 2 1]]


In [15]:
d3 = np.random.randint(0, 3, (4, 3)) 
print(d3)

[[0 0 0]
 [1 1 0]
 [1 2 2]
 [1 1 2]]


In [16]:
print(d2 + d3)

[[5 8 0]
 [4 7 2]
 [2 6 7]
 [2 3 3]]


In [17]:
d1 = np.random.randint(0, 3, (1, 3)) 
print(d1)

[[1 0 2]]


In [18]:
print(d2 + d1)

[[6 8 2]
 [4 6 4]
 [2 4 7]
 [2 2 3]]


In [19]:
d5 = np.random.randint(0, 3, (4, 1)) 
print(d5)

[[0]
 [2]
 [0]
 [0]]


In [20]:
print(d2 + d5)

[[5 8 0]
 [5 8 4]
 [1 4 5]
 [1 2 1]]


##Flatting array

In [22]:
a = np.random.randint(0, 8, (2, 3)) 
print(a)

[[6 4 6]
 [7 2 3]]


In [24]:
b = a.flatten()
print(b)
print(a)

[6 4 6 7 2 3]
[[6 4 6]
 [7 2 3]]


In [26]:
b[0]=9
print(b)
print(a) #no changed but in ravel function  it will be changed

[9 4 6 7 2 3]
[[6 4 6]
 [7 2 3]]


In [28]:
c = a.ravel()
print(c)

[6 4 6 7 2 3]


In [29]:
c[0]= 22
print(c)
print(a)

[22  4  6  7  2  3]
[[22  4  6]
 [ 7  2  3]]


#Sort

In [30]:
a = np.random.randint(0, 8, (3, 4)) 
print(a)

[[2 6 3 6]
 [5 1 4 2]
 [0 1 5 7]]


In [33]:
print(np.sort(a, axis=0)) #sort along row and copy

[[0 1 3 2]
 [2 1 4 6]
 [5 6 5 7]]


In [34]:
a.sort(axis=0) #sort along row and change
print(a)

[[0 1 3 2]
 [2 1 4 6]
 [5 6 5 7]]


##Manupulate array

In [35]:
a = np.random.randint(0, 8, (3, 4)) 
print(a)

[[3 7 7 5]
 [7 1 4 0]
 [6 7 0 5]]


In [36]:
print(a.T)

[[3 7 6]
 [7 1 7]
 [7 4 0]
 [5 0 5]]


In [37]:
a = np.random.randint(0, 8, (2, 3, 4)) 
print(a)

[[[4 5 2 7]
  [2 0 6 6]
  [2 5 0 0]]

 [[1 6 0 6]
  [0 0 7 0]
  [3 2 6 6]]]


In [38]:
print(a.transpose(1, 0, 2))

[[[4 5 2 7]
  [1 6 0 6]]

 [[2 0 6 6]
  [0 0 7 0]]

 [[2 5 0 0]
  [3 2 6 6]]]


Swap axis

In [40]:
a = np.random.randint(0, 8, (2, 3, 4)) 
print(a)

[[[7 4 0 5]
  [1 3 4 3]
  [5 2 5 4]]

 [[1 3 7 4]
  [3 0 7 6]
  [4 6 5 5]]]


In [42]:
print(a.swapaxes(1, 2))

[[[7 1 5]
  [4 3 2]
  [0 4 5]
  [5 3 4]]

 [[1 3 4]
  [3 0 6]
  [7 7 5]
  [4 6 5]]]


In [43]:
# change the shape of an array and return a copy
a.reshape((4,6))

array([[7, 4, 0, 5, 1, 3],
       [4, 3, 5, 2, 5, 4],
       [1, 3, 7, 4, 3, 0],
       [7, 6, 4, 6, 5, 5]])

In [0]:
# change the shape of an array in place
a.resize((4,6))

Append elements in array

In [0]:
arr = np.array([1,2,3])

In [46]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


Insert element in array

In [47]:
arr3 = np.insert(arr, 1, 100)    
print(arr3)

[  1 100   2   3]


In [48]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


Delete element

In [49]:
print(arr)
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[1 2 3]
[2 3]


In [50]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


Copy an array

In [0]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

#Combine and Split

In [52]:
a = np.random.randint(0, 8, (2, 3))
b = np.random.randint(0, 8, (2, 3))
c = np.random.randint(0, 8, (2, 1)) 
d = np.random.randint(0, 8, (1, 3)) 
 
print(a)
print(b)
print(c)
print(d)

[[1 6 5]
 [6 0 4]]
[[7 2 5]
 [1 5 3]]
[[2]
 [3]]
[[4 3 4]]


In [53]:
x = np.concatenate((a, b), axis=1)
print(x) 

[[1 6 5 7 2 5]
 [6 0 4 1 5 3]]


In [55]:
y = np.concatenate((a, c), axis=1)
z = np.concatenate((a, d), axis=0)

print(y) 
print(z) 


[[1 6 5 2]
 [6 0 4 3]]
[[1 6 5]
 [6 0 4]
 [4 3 4]]


In [56]:
# stack arrays vertically
cat = np.vstack((a, b))
print(cat)

[[1 6 5]
 [6 0 4]
 [7 2 5]
 [1 5 3]]


In [58]:
# stack arrays vertically
cat = np.r_[a, b]
print(cat)

[[1 6 5]
 [6 0 4]
 [7 2 5]
 [1 5 3]]


In [59]:
cat = np.hstack((a, b))
print(cat)

[[1 6 5 7 2 5]
 [6 0 4 1 5 3]]


In [60]:
cat = np.c_[a, b]
print(cat)

[[1 6 5 7 2 5]
 [6 0 4 1 5 3]]


Split array

In [61]:
a = np.random.randint(0, 8, (4, 6))
print(a)

[[1 7 5 0 0 1]
 [2 6 1 5 6 5]
 [7 1 7 4 2 1]
 [2 5 2 4 6 1]]


In [63]:
b = np.vsplit(a, 2)
print(b)

[array([[1, 7, 5, 0, 0, 1],
       [2, 6, 1, 5, 6, 5]]), array([[7, 1, 7, 4, 2, 1],
       [2, 5, 2, 4, 6, 1]])]


In [66]:
b = np.hsplit(a, 2)
print(b)

[array([[1, 7, 5],
       [2, 6, 1],
       [7, 1, 7],
       [2, 5, 2]]), array([[0, 0, 1],
       [5, 6, 5],
       [4, 2, 1],
       [4, 6, 1]])]


In [68]:
c = np.hsplit(a, 3)
print(c)

[array([[1, 7],
       [2, 6],
       [7, 1],
       [2, 5]]), array([[5, 0],
       [1, 5],
       [7, 4],
       [2, 4]]), array([[0, 1],
       [6, 5],
       [2, 1],
       [6, 1]])]
